SPECTACULAR_SETTINGS = {
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Story Users",
    "DESCRIPTION": "User microservices",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}
